import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRseHpxYXJ0am5ldnNpaGRxeXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzMjEyNzIsImV4cCI6MjA4OTg5NzI3Mn0.Xol5jvsyyiL2OUki6QhCffxVDZLaOxYR_jRijgZ1Kfg'
const supabaseKey = 'sb_publishable_vpoRKTgn2ZsaZ0Fx19yMiA_pGnipxYd'

export const supabase = createClient(supabaseUrl, supabaseKey)
